# This contains snippets of LaTeX to be used in compiling an algebra homework document

doc_header = """\\documentclass[12pt, fleqn]{article}
\\usepackage[a4paper,
            bindingoffset=0.2in,
            left=0.5in,
            right=0.5in,
            top=0.5in,
            bottom=0.5in,
            footskip=.25in]{geometry}
\\usepackage{amsmath}
\\begin{document}
\\pagenumbering{gobble}"""


page_header = """% Using makebox and \\vspace* to manually add the title and date
\\noindent\\makebox[\\textwidth]{
  \\large\\textbf{Algebra} \\noindent\\textbf{(INSERT_STUDENT_HERE)}%
  \\hfill%
  INSERT_DATE_HERE
}

\\vspace*{2em}
\\begin{enumerate}"""

