# Used by: rob.anagram via rob.utilities.cli

hidden_options = ["show_python_signature", "h", "help", "open_base_config", "edit_cli_config"]

[options]
help = false
h = false
capture_output = true
edit_cli_config = false
open_cli_config = false
open_base_config = false
show_python_signature = true
