# Used by: rob.homework via rob.utilities.cli

hidden_options = [ "edit_cli_config", "open_base_config", "capture_output", "h", "show_python_signature"]

[options]
help = false
h = false
capture_output = false
edit_cli_config = false
open_cli_config = false
open_base_config = false
show_python_signature = false
